### PR TITLE
Rewrite pressure converter in C++

### PR DESCRIPTION
**Pull request by timonegk**
## Proposed changes
The current pressure converter in python is not very efficient, therefore the pressure converter was rewritten.

## Necessary checks
- [x] Update package version
- [x] Run `catkin build`
- [ ] Write documentation
- [ ] Create issues for future work
- [x] Test on your machine
- [ ] Test on the robot
- [x] Put the PR on our Project board

### CODE REVIEW

**Comment by SammyRamone** [comment]
the calibration method could be improved in the futur., I made an issue in the backlog https://github.com/bit-bots/bitbots_lowlevel/issues/54

**Review by SammyRamone — DISMISSED** [review]

**Comment by jgueldenstein** [comment]
I have fixed a minor bug and adapted the launch script of ros control to start the new pressure converter.

I have also tested the code in visualization and it works as intended.

**Review by SammyRamone — DISMISSED** [review]

**Comment by timonegk** [comment]
rviz is dying when I try to display the wrenches. Maybe someone else can test this? It might be due to my setup.

**Comment by jgueldenstein** [comment]
We should publish the force in newtons instead of kg according to the ROS standard

**Review by SammyRamone — DISMISSED** [review]

**Review by SammyRamone — APPROVED** [review]

**Pull request merged**
